basePath: /
definitions:
  CharactersResponse:
    properties:
      characters:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      lastSync:
        type: string
    type: object
  CollaboratorsResponse:
    properties:
      colorists:
        items:
          type: string
        type: array
      editors:
        items:
          type: string
        type: array
      lastSync:
        type: string
      writers:
        items:
          type: string
        type: array
    type: object
info:
  contact:
    email: juanmesp@hotmail.com
    name: Juan Espinoza
  description: albomx-comics API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: albomx-comics API
  version: 1.0.0
paths:
  /characters:
    get:
      consumes:
      - application/json
      description: Get characters info
      parameters:
      - description: To who am i getting?
        in: query
        name: avengerId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CharactersResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: get
      tags:
      - Albomxcomics
  /collaborators:
    get:
      consumes:
      - application/json
      description: Get collaborators info
      parameters:
      - description: To who am i getting?
        in: query
        name: avengerId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CollaboratorsResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: get
      tags:
      - Albomxcomics
swagger: "2.0"
tags:
- description: All the available albomx-comics operations
  name: Albomxcomics
